### ISSUE TITLE
Enabling a routing channel gives Incorrect Reference error

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#131]
Reproduction Steps:

1. Create a routing channel
2. Disable it via toolbar button or right-click menu
3. Enable routing channel....notice error

![image](https://user-images.githubusercontent.com/29433053/67243417-19777980-f41d-11e9-8c08-5c981c6894ae.png)

**Comment by buckd** [comment]
I can't reproduce this. I did see this during development, but put in a change that should have fixed it. Can you reliably reproduce this on your machine?

**Comment by buckd** [comment]
This is a race condition in System Explorer. In the GUID validation, we ensure the current GUID is either an enabled channel or a disabled channel. But before we do that check, we set the new GUID.

The problem is that in the check for an enabled channel, the GUID is for the disabled channel, but by the time we check the disabled GUID, the channel now says it's enabled, so both checks fail even though the GUIDs are actually valid.
