### ISSUE TITLE
Issue Configuring SET-2010 for different topologies

### ISSUE THREAD

**Issue by skthelimit** [ni/niveristand-routing-and-faulting-custom-device#192]
**Describe the bug**
Setup: SLSC connected via local nework. Using Veristand 2019 R3 f1. 
Description: When I select different topologies for SET-2010, error -1074114556 appears. 

**To Reproduce**

1. Open Veristand 2019 R3 f1. Create System definition file
2. Under Hardware/SLSC, right click -> Add SLSC Chassis. Connect with -> Hostname or IP Address. Hostname or IP Address -> IP address of SLSC Chassis.
3. Go to Modules. Select 'SLSC Switch' on Slot 1
4. Go to Slot 1 (SLSC Switch) node. Then click 'Autodetect' menu item. After a few seconds, you should see Model Number -> "SET-2010: 64 CH Routing Base SLSC Card" and Topology -> BaseCard
5. So far so good. 
6. Now expand 'Slot 1 (SLSC Switch)' node. Then select 'Endpoint Configuration' node. You should see many items in the Endpoint list, each of which has 'Load (Default)' configuration assigned. Now scroll the list all the way down. After "XJ2Ch31n" endpoint, there are Instrument & Fault items such as 'XJ3Inst0p' and 'XJ3FaultD'. (Good)
7.  Now under Custom Devices, create Routing and Faulting Custom Device
8. Go to Routing and Faulting/Endpoint Aliases
9. Click on Endpoint dropdown listbox, and check what's available. **Notice that endpoints from J1Ch0p to XJ2Ch31n are all listed in the endpoints, but no instrument or fault items (such as 'XJ3Inst0p' or 'XJ3FaultD') are populated in the dropdown listbox. (Bad)** Do not add anything here and go to the next step.
10. Now, go back to Hardware/SLSC/SLSCChassis/Modules/Slot 1 (SLSC Switch)
11. In the UI, change the Topology setting from 'BaseCard' to 'Slot2FaultCard' Error -1074114556 shows up. As a result, after the error occurs, click on the Slot 1 (SLSC Switch)/Endpoint Configuration node. The Endpoint list is now empty.

**Expected behavior**
At step 9, I should see the Instrument endpoints and Fault items. 
At step 11, the error should not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/1081947/83089567-74282200-a04b-11ea-90fc-98d2238a5482.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Veristand 2019 R3 f1

**Additional context**
My goal is to use SET-2010 such that my signals going through the module into Fault state.

**Comment by skthelimit** [comment]
FYI: I posted the same issue on NI forum [here](https://forums.ni.com/t5/NI-VeriStand/Error-1074114556-on-Veristand-2019-R3-when-configuring-SET-2010/m-p/4054302?profile.language=en)

**Comment by rtzoeller** [comment]
Unfortunately this is a compatibility issue between the legacy topology format on the SET-2010 and the NI-SLSC Switch driver.

The SET-2010 was originally designed to work with an unofficial SLSC switching library, which allowed for the selection of multiple topologies simultaneously. When NI-SLSC Switch was created, the decision was made to follow NI-SWITCH's precedent and only allow for a single topology to be active. As a side-effect, the legacy daughter-card topologies on the SET-2010 are underspecified for NI-SLSC Switch, as they rely on the BaseCard topology being active as well. Only the default (BaseCard) topology will work out of the box.

The NI-SLSC Switch API does provide a way to use a custom JSON switch definition, rather than using the JSON stored on the module directly. The SLSC Switch custom device makes use of this; if you configure the module by using "Load from JSON" rather than auto-detecting, that JSON file will also be used at runtime.

You can attempt to create your own JSON file that "combines" the topology definitions from the SET-2010 (the BaseCard topology and whichever daughter card topologies are needed), and use the combined topology to configure the custom device and deploy. The format for the SLSC Switch JSON definition is described in the SLSC MDK; the JSON definitions for the SLSC-12251 and 12252 are installed as examples to `C:\Program Files (x86)\National Instruments\Shared\NI-SLSC Switch\Modules`.

Alternatively you could use the [SLSC EDS custom device](https://github.com/ni/niveristand-slsc-eds-custom-device) to control the modules, rather than this custom device.

**Comment by skthelimit** [comment]
@rtzoeller thank you for explaining what's causing this issue. I will see if I can create my own JSON file.

**Comment by skthelimit** [comment]
Hi @rtzoeller I am not sure if this issue should stay open or be closed. Please advise.

**Comment by rtzoeller** [comment]
Thanks for following up on this; it can be closed.
