### ISSUE TITLE
Add Routing Channel adds empty channel if parameters are invalid

### ISSUE THREAD

**Issue by csjall** [ni/niveristand-routing-and-faulting-custom-device#49]
**Describe the bug**
The Scripting API has an entry point to add routing channels. As part of the adding the channel we checking the input parameters for unique parameters. If the validation fails the channel remains added to the system definition file.

**To Reproduce**
1. Open unit test `test Add RAF Channel.vi`
1. Click `Save Control?` button on front panel
1. Run the unit test using VI Tester
1. Open the resulting system definition file in VeriStand.
1. Note that `RouteChan0` is present in VeriStand.

**Expected behavior**
A partially formatted channel should not be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/4081815/64540439-d9818a80-d2e5-11e9-93f2-79d913fa7290.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by mdcerna** [comment]
This issue will be fixed by PR #95 .  But after this issue was created, the default values for the input parameters (so, unwired behavior) leads to a valid parameter set with the Initial State = No Connections.  
RouteChan0 will be valid and correctly created.
RouteChan1 is *invalid* (non-unique State Values) and should not be created.
RouteChan1 is valid as before.
